#!/bin/sh
# chkconfig: 2345 95 20
# description: OpenNode Management Server startup skript
# processname: omsd

DAEMON=/opt/oms/bin/omsd
PIDFILE=/var/run/omsd.pid
LOGFILE=/var/log/omsd

if [ -f /lib/lsb/init-functions ]; then
    . /lib/lsb/init-functions
fi

case $1 in
    start)
        if [ -f /etc/debian_version ]; then
            log_begin_msg "Staring omsd daemon:"
            start-stop-daemon --start --make-pid --pidfile $PIDFILE --exec $DAEMON --background -- --log $LOGFILE
            RETVAL=$?
            log_end_msg $RETVAL
        else
            echo -n "Staring omsd daemon..."
            $DAEMON --log $LOGFILE >/dev/null 2>&1 &
            PID=$!
            RETVAL=$?
            echo $PID >$PIDFILE
            echo
        fi
            ;;

    stop)
        if [ -f /etc/debian_version ]; then
            log_begin_msg "Stopping omsd daemon:"
            start-stop-daemon --stop --signal TERM --pidfile $PIDFILE
            RETVAL=$?
            log_end_msg $RETVAL
            ps xa|grep '[r]unzeo' | awk '{print $1}' | xargs kill
        else
            echo -n "Stopping omsd daemon..."

            if [ -f "$PIDFILE" ]; then
                kill -TERM $(cat $PIDFILE)
                rm $PIDFILE
            fi
            ps xa|grep '[r]unzeo' | awk '{print $1}' | xargs kill
            echo
        fi
    ;;
  restart)

    ${0} stop
    sleep 1
    ${0} start

    ;;
  *)

    echo "usage ${0} {start|stop|restart}"

    ;;
esac
