#!/usr/bin/env python
# EASY-INSTALL-ENTRY-SCRIPT: 'Sphinx==1.1.2','console_scripts','sphinx-apidoc'
__requires__ = 'Sphinx==1.1.2'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('Sphinx==1.1.2', 'console_scripts', 'sphinx-apidoc')()
    )
